# Generated by Django 3.0.2 on 2020-01-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='News',
        ),
    ]
