# Generated by Django 3.0.2 on 2020-02-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200130_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picname',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
