# Generated by Django 3.0.2 on 2020-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.TextField(default='-'),
        ),
    ]
