# Generated by Django 3.0.2 on 2020-04-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200420_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
