# Generated by Django 3.0.2 on 2020-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200420_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='confirm',
            field=models.IntegerField(default=0),
        ),
    ]
