# Generated by Django 3.0.2 on 2020-04-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_auto_20200420_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
