# Generated by Django 3.0.2 on 2020-04-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200127_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picurl',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl2',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
