# Generated by Django 3.0.2 on 2020-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200420_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picname',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='main',
            name='picname2',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
